org: ciaran
app: rest-api-app
service: secret-sharer

# Create an optimized package for our functions
package:
  individually: true

plugins:
  # Package our functions with Webpack
  - serverless-bundle
  - serverless-offline
  # Load .env as environment variables
  - serverless-dotenv-plugin 

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  ciphersTableName: ${self:custom.stage}-ciphers
  customersTableName: ${self:custom.stage}-ciphers
  
provider:
  name: aws
  # development only, use --aws-profile profilename instead
  profile: ct-prod-serverless
  runtime: nodejs12.x
  stage: dev
  # development only
  region: ap-southeast-2
  tracing:
    apiGateway: true
    lambda: true

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}
    environment:  dev
    GETSECRET_URL: https://secret-sharer-client.s3-ap-southeast-2.amazonaws.com/getsecret.html?id=
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}
    businessSubscriptionPriceId: ${env:STRIPE_BUSINESS_SUBSCRIPTION_PRICE_ID}
    enterpriseSubscriptionPriceId: ${env:STRIPE_ENTERPRISE_SUBSCRIPTION_PRICE_ID}
    domainURL: ${env:DOMAIN_URL}
    
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      #Development only, restrict for production
        - "ssm:*" 
        - "ssm:PutParameter"
        - "ssm:GetParameter"
      Resource: ["arn:aws:ssm:*:*:*"]
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: ["arn:aws:ssm:*:*:*"]
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Development only, restrict for production
      Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"

functions:

  create:
    handler: create.main
    events:
      - http:
          path: putSecret
          method: post
          cors: true
          # authorizer: aws_iam (not auth  for dev, consider for  production)
  get:
    handler: get.main
    events:
      - http:
          path: getsecret
          method: post
          cors: true
          # authorizer: aws_iam (not auth  for dev, consider for  production)

  billing:
    # Defines an HTTP API endpoint that calls the main function in billing.js
    # - path: url path is /billing
    # - method: POST request
    handler: billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam

  create-checkout-session:
    # Defines an HTTP API endpoint that calls the main function in create-checkout-session.js
    # - path: url path is /create-checkout-session
    # - method: POST request
    handler: create-checkout-session.main
    events:
      - http:
          path: create-checkout-session
          method: post
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
