Resources:
  SecretsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdBy
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
          - IndexName: createdBy-index
            KeySchema:
              - AttributeName: createdBy
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTableName}
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: customer_email
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
      GlobalSecondaryIndexes:
          - IndexName: customer_email-index
            KeySchema:
              - AttributeName: customer_email
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  InvitesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.invitesTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
          - IndexName: teamId-index
            KeySchema:
              - AttributeName: teamId
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
