Resources:
  SecretsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.ciphersTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.customersTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST